// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: status.proto

package statuspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"kiyudesign.com/cesnow/light-server/pkg/tproto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RpcStatus_StatusSetSessionOnline_FullMethodName      = "/status.RpcStatus/status_setSessionOnline"
	RpcStatus_StatusSetSessionOffline_FullMethodName     = "/status.RpcStatus/status_setSessionOffline"
	RpcStatus_StatusGetUserOnlineSessions_FullMethodName = "/status.RpcStatus/status_getUserOnlineSessions"
)

// RpcStatusClient is the client API for RpcStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcStatusClient interface {
	StatusSetSessionOnline(ctx context.Context, in *TStatusSetSessionOnline, opts ...grpc.CallOption) (*tproto.Bool, error)
	StatusSetSessionOffline(ctx context.Context, in *TStatusSetSessionOffline, opts ...grpc.CallOption) (*tproto.Bool, error)
	StatusGetUserOnlineSessions(ctx context.Context, in *TStatusGetUserOnlineSessions, opts ...grpc.CallOption) (*UserSessionEntryList, error)
}

type rpcStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcStatusClient(cc grpc.ClientConnInterface) RpcStatusClient {
	return &rpcStatusClient{cc}
}

func (c *rpcStatusClient) StatusSetSessionOnline(ctx context.Context, in *TStatusSetSessionOnline, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcStatus_StatusSetSessionOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcStatusClient) StatusSetSessionOffline(ctx context.Context, in *TStatusSetSessionOffline, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcStatus_StatusSetSessionOffline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcStatusClient) StatusGetUserOnlineSessions(ctx context.Context, in *TStatusGetUserOnlineSessions, opts ...grpc.CallOption) (*UserSessionEntryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSessionEntryList)
	err := c.cc.Invoke(ctx, RpcStatus_StatusGetUserOnlineSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcStatusServer is the server API for RpcStatus service.
// All implementations should embed UnimplementedRpcStatusServer
// for forward compatibility
type RpcStatusServer interface {
	StatusSetSessionOnline(context.Context, *TStatusSetSessionOnline) (*tproto.Bool, error)
	StatusSetSessionOffline(context.Context, *TStatusSetSessionOffline) (*tproto.Bool, error)
	StatusGetUserOnlineSessions(context.Context, *TStatusGetUserOnlineSessions) (*UserSessionEntryList, error)
}

// UnimplementedRpcStatusServer should be embedded to have forward compatible implementations.
type UnimplementedRpcStatusServer struct {
}

func (UnimplementedRpcStatusServer) StatusSetSessionOnline(context.Context, *TStatusSetSessionOnline) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusSetSessionOnline not implemented")
}
func (UnimplementedRpcStatusServer) StatusSetSessionOffline(context.Context, *TStatusSetSessionOffline) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusSetSessionOffline not implemented")
}
func (UnimplementedRpcStatusServer) StatusGetUserOnlineSessions(context.Context, *TStatusGetUserOnlineSessions) (*UserSessionEntryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusGetUserOnlineSessions not implemented")
}

// UnsafeRpcStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcStatusServer will
// result in compilation errors.
type UnsafeRpcStatusServer interface {
	mustEmbedUnimplementedRpcStatusServer()
}

func RegisterRpcStatusServer(s grpc.ServiceRegistrar, srv RpcStatusServer) {
	s.RegisterService(&RpcStatus_ServiceDesc, srv)
}

func _RpcStatus_StatusSetSessionOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TStatusSetSessionOnline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcStatusServer).StatusSetSessionOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcStatus_StatusSetSessionOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcStatusServer).StatusSetSessionOnline(ctx, req.(*TStatusSetSessionOnline))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcStatus_StatusSetSessionOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TStatusSetSessionOffline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcStatusServer).StatusSetSessionOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcStatus_StatusSetSessionOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcStatusServer).StatusSetSessionOffline(ctx, req.(*TStatusSetSessionOffline))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcStatus_StatusGetUserOnlineSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TStatusGetUserOnlineSessions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcStatusServer).StatusGetUserOnlineSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcStatus_StatusGetUserOnlineSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcStatusServer).StatusGetUserOnlineSessions(ctx, req.(*TStatusGetUserOnlineSessions))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcStatus_ServiceDesc is the grpc.ServiceDesc for RpcStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "status.RpcStatus",
	HandlerType: (*RpcStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "status_setSessionOnline",
			Handler:    _RpcStatus_StatusSetSessionOnline_Handler,
		},
		{
			MethodName: "status_setSessionOffline",
			Handler:    _RpcStatus_StatusSetSessionOffline_Handler,
		},
		{
			MethodName: "status_getUserOnlineSessions",
			Handler:    _RpcStatus_StatusGetUserOnlineSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status.proto",
}
