// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"kiyudesign.com/cesnow/light-server/pkg/tproto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RpcSync_SyncPushUpdates_FullMethodName   = "/sync.RpcSync/sync_pushUpdates"
	RpcSync_SyncPushRpcResult_FullMethodName = "/sync.RpcSync/sync_pushRpcResult"
)

// RpcSyncClient is the client API for RpcSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcSyncClient interface {
	SyncPushUpdates(ctx context.Context, in *TSyncPushUpdates, opts ...grpc.CallOption) (*tproto.Void, error)
	SyncPushRpcResult(ctx context.Context, in *TSyncPushRpcResult, opts ...grpc.CallOption) (*tproto.Void, error)
}

type rpcSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcSyncClient(cc grpc.ClientConnInterface) RpcSyncClient {
	return &rpcSyncClient{cc}
}

func (c *rpcSyncClient) SyncPushUpdates(ctx context.Context, in *TSyncPushUpdates, opts ...grpc.CallOption) (*tproto.Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Void)
	err := c.cc.Invoke(ctx, RpcSync_SyncPushUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSyncClient) SyncPushRpcResult(ctx context.Context, in *TSyncPushRpcResult, opts ...grpc.CallOption) (*tproto.Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Void)
	err := c.cc.Invoke(ctx, RpcSync_SyncPushRpcResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcSyncServer is the server API for RpcSync service.
// All implementations should embed UnimplementedRpcSyncServer
// for forward compatibility
type RpcSyncServer interface {
	SyncPushUpdates(context.Context, *TSyncPushUpdates) (*tproto.Void, error)
	SyncPushRpcResult(context.Context, *TSyncPushRpcResult) (*tproto.Void, error)
}

// UnimplementedRpcSyncServer should be embedded to have forward compatible implementations.
type UnimplementedRpcSyncServer struct {
}

func (UnimplementedRpcSyncServer) SyncPushUpdates(context.Context, *TSyncPushUpdates) (*tproto.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncPushUpdates not implemented")
}
func (UnimplementedRpcSyncServer) SyncPushRpcResult(context.Context, *TSyncPushRpcResult) (*tproto.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncPushRpcResult not implemented")
}

// UnsafeRpcSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcSyncServer will
// result in compilation errors.
type UnsafeRpcSyncServer interface {
	mustEmbedUnimplementedRpcSyncServer()
}

func RegisterRpcSyncServer(s grpc.ServiceRegistrar, srv RpcSyncServer) {
	s.RegisterService(&RpcSync_ServiceDesc, srv)
}

func _RpcSync_SyncPushUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSyncPushUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSyncServer).SyncPushUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSync_SyncPushUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSyncServer).SyncPushUpdates(ctx, req.(*TSyncPushUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSync_SyncPushRpcResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSyncPushRpcResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSyncServer).SyncPushRpcResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSync_SyncPushRpcResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSyncServer).SyncPushRpcResult(ctx, req.(*TSyncPushRpcResult))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcSync_ServiceDesc is the grpc.ServiceDesc for RpcSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.RpcSync",
	HandlerType: (*RpcSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sync_pushUpdates",
			Handler:    _RpcSync_SyncPushUpdates_Handler,
		},
		{
			MethodName: "sync_pushRpcResult",
			Handler:    _RpcSync_SyncPushRpcResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
