// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: session.proto

package sessionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	tproto "kiyudesign.com/cesnow/light-server/pkg/tproto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RpcSession_SessionQueryAuthId_FullMethodName            = "/session.RpcSession/session_queryAuthId"
	RpcSession_SessionCreateSession_FullMethodName          = "/session.RpcSession/session_createSession"
	RpcSession_SessionSendDataToSession_FullMethodName      = "/session.RpcSession/session_sendDataToSession"
	RpcSession_SessionSendHttpDataToSession_FullMethodName  = "/session.RpcSession/session_sendHttpDataToSession"
	RpcSession_SessionCloseSession_FullMethodName           = "/session.RpcSession/session_closeSession"
	RpcSession_SessionPushUpdatesData_FullMethodName        = "/session.RpcSession/session_pushUpdatesData"
	RpcSession_SessionPushSessionUpdatesData_FullMethodName = "/session.RpcSession/session_pushSessionUpdatesData"
	RpcSession_SessionPushRpcResultData_FullMethodName      = "/session.RpcSession/session_pushRpcResultData"
)

// RpcSessionClient is the client API for RpcSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcSessionClient interface {
	SessionQueryAuthId(ctx context.Context, in *TSessionQueryAuthId, opts ...grpc.CallOption) (*tproto.AuthIdInfo, error)
	SessionCreateSession(ctx context.Context, in *TSessionCreateSession, opts ...grpc.CallOption) (*tproto.Bool, error)
	SessionSendDataToSession(ctx context.Context, in *TSessionSendDataToSession, opts ...grpc.CallOption) (*tproto.Bool, error)
	SessionSendHttpDataToSession(ctx context.Context, in *TSessionSendHttpDataToSession, opts ...grpc.CallOption) (*HttpSessionData, error)
	SessionCloseSession(ctx context.Context, in *TSessionCloseSession, opts ...grpc.CallOption) (*tproto.Bool, error)
	SessionPushUpdatesData(ctx context.Context, in *TSessionPushUpdatesData, opts ...grpc.CallOption) (*tproto.Bool, error)
	SessionPushSessionUpdatesData(ctx context.Context, in *TSessionPushSessionUpdatesData, opts ...grpc.CallOption) (*tproto.Bool, error)
	SessionPushRpcResultData(ctx context.Context, in *TSessionPushRpcResultData, opts ...grpc.CallOption) (*tproto.Bool, error)
}

type rpcSessionClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcSessionClient(cc grpc.ClientConnInterface) RpcSessionClient {
	return &rpcSessionClient{cc}
}

func (c *rpcSessionClient) SessionQueryAuthId(ctx context.Context, in *TSessionQueryAuthId, opts ...grpc.CallOption) (*tproto.AuthIdInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.AuthIdInfo)
	err := c.cc.Invoke(ctx, RpcSession_SessionQueryAuthId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionCreateSession(ctx context.Context, in *TSessionCreateSession, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionCreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionSendDataToSession(ctx context.Context, in *TSessionSendDataToSession, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionSendDataToSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionSendHttpDataToSession(ctx context.Context, in *TSessionSendHttpDataToSession, opts ...grpc.CallOption) (*HttpSessionData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpSessionData)
	err := c.cc.Invoke(ctx, RpcSession_SessionSendHttpDataToSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionCloseSession(ctx context.Context, in *TSessionCloseSession, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionCloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionPushUpdatesData(ctx context.Context, in *TSessionPushUpdatesData, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionPushUpdatesData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionPushSessionUpdatesData(ctx context.Context, in *TSessionPushSessionUpdatesData, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionPushSessionUpdatesData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcSessionClient) SessionPushRpcResultData(ctx context.Context, in *TSessionPushRpcResultData, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcSession_SessionPushRpcResultData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcSessionServer is the server API for RpcSession service.
// All implementations should embed UnimplementedRpcSessionServer
// for forward compatibility
type RpcSessionServer interface {
	SessionQueryAuthId(context.Context, *TSessionQueryAuthId) (*tproto.AuthIdInfo, error)
	SessionCreateSession(context.Context, *TSessionCreateSession) (*tproto.Bool, error)
	SessionSendDataToSession(context.Context, *TSessionSendDataToSession) (*tproto.Bool, error)
	SessionSendHttpDataToSession(context.Context, *TSessionSendHttpDataToSession) (*HttpSessionData, error)
	SessionCloseSession(context.Context, *TSessionCloseSession) (*tproto.Bool, error)
	SessionPushUpdatesData(context.Context, *TSessionPushUpdatesData) (*tproto.Bool, error)
	SessionPushSessionUpdatesData(context.Context, *TSessionPushSessionUpdatesData) (*tproto.Bool, error)
	SessionPushRpcResultData(context.Context, *TSessionPushRpcResultData) (*tproto.Bool, error)
}

// UnimplementedRpcSessionServer should be embedded to have forward compatible implementations.
type UnimplementedRpcSessionServer struct {
}

func (UnimplementedRpcSessionServer) SessionQueryAuthId(context.Context, *TSessionQueryAuthId) (*tproto.AuthIdInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionQueryAuthId not implemented")
}
func (UnimplementedRpcSessionServer) SessionCreateSession(context.Context, *TSessionCreateSession) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionCreateSession not implemented")
}
func (UnimplementedRpcSessionServer) SessionSendDataToSession(context.Context, *TSessionSendDataToSession) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionSendDataToSession not implemented")
}
func (UnimplementedRpcSessionServer) SessionSendHttpDataToSession(context.Context, *TSessionSendHttpDataToSession) (*HttpSessionData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionSendHttpDataToSession not implemented")
}
func (UnimplementedRpcSessionServer) SessionCloseSession(context.Context, *TSessionCloseSession) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionCloseSession not implemented")
}
func (UnimplementedRpcSessionServer) SessionPushUpdatesData(context.Context, *TSessionPushUpdatesData) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionPushUpdatesData not implemented")
}
func (UnimplementedRpcSessionServer) SessionPushSessionUpdatesData(context.Context, *TSessionPushSessionUpdatesData) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionPushSessionUpdatesData not implemented")
}
func (UnimplementedRpcSessionServer) SessionPushRpcResultData(context.Context, *TSessionPushRpcResultData) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionPushRpcResultData not implemented")
}

// UnsafeRpcSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcSessionServer will
// result in compilation errors.
type UnsafeRpcSessionServer interface {
	mustEmbedUnimplementedRpcSessionServer()
}

func RegisterRpcSessionServer(s grpc.ServiceRegistrar, srv RpcSessionServer) {
	s.RegisterService(&RpcSession_ServiceDesc, srv)
}

func _RpcSession_SessionQueryAuthId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionQueryAuthId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionQueryAuthId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionQueryAuthId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionQueryAuthId(ctx, req.(*TSessionQueryAuthId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionCreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionCreateSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionCreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionCreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionCreateSession(ctx, req.(*TSessionCreateSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionSendDataToSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionSendDataToSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionSendDataToSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionSendDataToSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionSendDataToSession(ctx, req.(*TSessionSendDataToSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionSendHttpDataToSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionSendHttpDataToSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionSendHttpDataToSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionSendHttpDataToSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionSendHttpDataToSession(ctx, req.(*TSessionSendHttpDataToSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionCloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionCloseSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionCloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionCloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionCloseSession(ctx, req.(*TSessionCloseSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionPushUpdatesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionPushUpdatesData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionPushUpdatesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionPushUpdatesData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionPushUpdatesData(ctx, req.(*TSessionPushUpdatesData))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionPushSessionUpdatesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionPushSessionUpdatesData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionPushSessionUpdatesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionPushSessionUpdatesData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionPushSessionUpdatesData(ctx, req.(*TSessionPushSessionUpdatesData))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcSession_SessionPushRpcResultData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSessionPushRpcResultData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcSessionServer).SessionPushRpcResultData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcSession_SessionPushRpcResultData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcSessionServer).SessionPushRpcResultData(ctx, req.(*TSessionPushRpcResultData))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcSession_ServiceDesc is the grpc.ServiceDesc for RpcSession service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcSession_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.RpcSession",
	HandlerType: (*RpcSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "session_queryAuthId",
			Handler:    _RpcSession_SessionQueryAuthId_Handler,
		},
		{
			MethodName: "session_createSession",
			Handler:    _RpcSession_SessionCreateSession_Handler,
		},
		{
			MethodName: "session_sendDataToSession",
			Handler:    _RpcSession_SessionSendDataToSession_Handler,
		},
		{
			MethodName: "session_sendHttpDataToSession",
			Handler:    _RpcSession_SessionSendHttpDataToSession_Handler,
		},
		{
			MethodName: "session_closeSession",
			Handler:    _RpcSession_SessionCloseSession_Handler,
		},
		{
			MethodName: "session_pushUpdatesData",
			Handler:    _RpcSession_SessionPushUpdatesData_Handler,
		},
		{
			MethodName: "session_pushSessionUpdatesData",
			Handler:    _RpcSession_SessionPushSessionUpdatesData_Handler,
		},
		{
			MethodName: "session_pushRpcResultData",
			Handler:    _RpcSession_SessionPushRpcResultData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
