// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"kiyudesign.com/cesnow/light-server/pkg/tproto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RpcGateway_GatewaySendDataToGateway_FullMethodName = "/gateway.RpcGateway/gateway_sendDataToGateway"
)

// RpcGatewayClient is the client API for RpcGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcGatewayClient interface {
	GatewaySendDataToGateway(ctx context.Context, in *TGatewaySendDataToGateway, opts ...grpc.CallOption) (*tproto.Bool, error)
}

type rpcGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcGatewayClient(cc grpc.ClientConnInterface) RpcGatewayClient {
	return &rpcGatewayClient{cc}
}

func (c *rpcGatewayClient) GatewaySendDataToGateway(ctx context.Context, in *TGatewaySendDataToGateway, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcGateway_GatewaySendDataToGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcGatewayServer is the server API for RpcGateway service.
// All implementations should embed UnimplementedRpcGatewayServer
// for forward compatibility
type RpcGatewayServer interface {
	GatewaySendDataToGateway(context.Context, *TGatewaySendDataToGateway) (*tproto.Bool, error)
}

// UnimplementedRpcGatewayServer should be embedded to have forward compatible implementations.
type UnimplementedRpcGatewayServer struct {
}

func (UnimplementedRpcGatewayServer) GatewaySendDataToGateway(context.Context, *TGatewaySendDataToGateway) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewaySendDataToGateway not implemented")
}

// UnsafeRpcGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcGatewayServer will
// result in compilation errors.
type UnsafeRpcGatewayServer interface {
	mustEmbedUnimplementedRpcGatewayServer()
}

func RegisterRpcGatewayServer(s grpc.ServiceRegistrar, srv RpcGatewayServer) {
	s.RegisterService(&RpcGateway_ServiceDesc, srv)
}

func _RpcGateway_GatewaySendDataToGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TGatewaySendDataToGateway)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcGatewayServer).GatewaySendDataToGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcGateway_GatewaySendDataToGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcGatewayServer).GatewaySendDataToGateway(ctx, req.(*TGatewaySendDataToGateway))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcGateway_ServiceDesc is the grpc.ServiceDesc for RpcGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.RpcGateway",
	HandlerType: (*RpcGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "gateway_sendDataToGateway",
			Handler:    _RpcGateway_GatewaySendDataToGateway_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
