// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "core_types.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Any } from "./any";
/**
 * @generated from protobuf message Bool
 */
export interface Bool {
    /**
     * @generated from protobuf field: bool value = 1;
     */
    value: boolean;
}
/**
 * @generated from protobuf message Void
 */
export interface Void {
}
/**
 * @generated from protobuf message RpcError
 */
export interface RpcError {
    /**
     * @generated from protobuf field: int32 error_code = 1;
     */
    errorCode: number;
    /**
     * @generated from protobuf field: string error_message = 2;
     */
    errorMessage: string;
}
/**
 * MsgRawData
 *
 * @generated from protobuf message MsgRawData
 */
export interface MsgRawData {
    /**
     * @generated from protobuf field: int32 seq_no = 1;
     */
    seqNo: number;
    /**
     * @generated from protobuf field: int64 msg_id = 2;
     */
    msgId: bigint;
    /**
     * @generated from protobuf field: int32 bytes = 3;
     */
    bytes: number;
    /**
     * @generated from protobuf field: int32 class_id = 4;
     */
    classId: number;
    /**
     * @generated from protobuf field: bytes body = 5;
     */
    body: Uint8Array;
}
/**
 * TMsgRawDataContainer
 *
 * @generated from protobuf message TMsgRawDataContainer
 */
export interface TMsgRawDataContainer {
    /**
     * @generated from protobuf field: repeated MsgRawData messages = 1;
     */
    messages: MsgRawData[];
}
/**
 * TMessage
 *
 * @generated from protobuf message TMessage
 */
export interface TMessage {
    /**
     * @generated from protobuf field: int32 seq_no = 1;
     */
    seqNo: number;
    /**
     * @generated from protobuf field: int64 msg_id = 2;
     */
    msgId: bigint;
    /**
     * @generated from protobuf field: int32 bytes = 3;
     */
    bytes: number;
    /**
     * @generated from protobuf field: google.protobuf.Any object = 4;
     */
    object?: Any;
}
/**
 * TMsgContainer
 *
 * @generated from protobuf message TMsgContainer
 */
export interface TMsgContainer {
    /**
     * @generated from protobuf field: repeated TMessage messages = 1;
     */
    messages: TMessage[];
}
/**
 * TGzipPacked
 *
 * @generated from protobuf message TGzipPacked
 */
export interface TGzipPacked {
    /**
     * @generated from protobuf field: bytes packed_data = 1;
     */
    packedData: Uint8Array;
    /**
     * @generated from protobuf field: google.protobuf.Any obj = 2;
     */
    obj?: Any;
}
/**
 * RpcResult
 *
 * @generated from protobuf message RpcResult
 */
export interface RpcResult {
    /**
     * @generated from protobuf field: int64 req_msg_id = 1;
     */
    reqMsgId: bigint;
    /**
     * @generated from protobuf field: google.protobuf.Any result = 2;
     */
    result?: Any;
}
/**
 * @generated from protobuf message TMsgAck
 */
export interface TMsgAck {
    /**
     * @generated from protobuf field: repeated int64 msg_ids = 2;
     */
    msgIds: bigint[];
}
/**
 * @generated from protobuf message BadMsgNotification
 */
export interface BadMsgNotification {
    /**
     * @generated from protobuf field: int64 bad_msg_id = 3;
     */
    badMsgId: bigint;
    /**
     * @generated from protobuf field: int32 bad_msg_seqno = 4;
     */
    badMsgSeqno: number;
    /**
     * @generated from protobuf field: int32 error_code = 5;
     */
    errorCode: number;
}
/**
 * @generated from protobuf message DestroySession
 */
export interface DestroySession {
    /**
     * @generated from protobuf field: int64 session_id = 3;
     */
    sessionId: bigint;
}
/**
 * @generated from protobuf message DestroySessionOk
 */
export interface DestroySessionOk {
    /**
     * @generated from protobuf field: DestroySession session = 1;
     */
    session?: DestroySession;
}
/**
 * @generated from protobuf message DestroySessionNone
 */
export interface DestroySessionNone {
    /**
     * @generated from protobuf field: DestroySession session = 1;
     */
    session?: DestroySession;
}
/**
 * @generated from protobuf message NewSessionCreated
 */
export interface NewSessionCreated {
    /**
     * @generated from protobuf field: int64 first_msg_id = 2;
     */
    firstMsgId: bigint;
    /**
     * @generated from protobuf field: int64 unique_id = 3;
     */
    uniqueId: bigint;
}
/**
 * @generated from protobuf message Ping
 */
export interface Ping {
    /**
     * @generated from protobuf field: int64 ping_id = 2;
     */
    pingId: bigint;
}
/**
 * @generated from protobuf message Pong
 */
export interface Pong {
    /**
     * @generated from protobuf field: int64 msg_id = 3;
     */
    msgId: bigint;
    /**
     * @generated from protobuf field: int64 ping_id = 4;
     */
    pingId: bigint;
}
/**
 * @generated from protobuf message InitConnection
 */
export interface InitConnection {
    /**
     * @generated from protobuf field: int32 api_id = 3;
     */
    apiId: number;
    /**
     * @generated from protobuf field: string device_model = 4;
     */
    deviceModel: string;
    /**
     * @generated from protobuf field: string system_version = 5;
     */
    systemVersion: string;
    /**
     * @generated from protobuf field: string app_version = 6;
     */
    appVersion: string;
    /**
     * @generated from protobuf field: string system_lang_code = 7;
     */
    systemLangCode: string;
    /**
     * @generated from protobuf field: string lang_pack = 8;
     */
    langPack: string;
    /**
     * @generated from protobuf field: string lang_code = 9;
     */
    langCode: string;
    /**
     * @generated from protobuf field: bytes query = 12;
     */
    query: Uint8Array;
}
/**
 * @generated from protobuf message AuthIdInfo
 */
export interface AuthIdInfo {
    /**
     * @generated from protobuf field: int64 auth_id = 3;
     */
    authId: bigint;
    /**
     * @generated from protobuf field: int64 session_id = 4;
     */
    sessionId: bigint;
    /**
     * @generated from protobuf field: bytes auth_key = 5;
     */
    authKey: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class Bool$Type extends MessageType<Bool> {
    constructor() {
        super("Bool", [
            { no: 1, name: "value", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Bool>): Bool {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.value = false;
        if (value !== undefined)
            reflectionMergePartial<Bool>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Bool): Bool {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool value */ 1:
                    message.value = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Bool, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool value = 1; */
        if (message.value !== false)
            writer.tag(1, WireType.Varint).bool(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Bool
 */
export const Bool = new Bool$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Void$Type extends MessageType<Void> {
    constructor() {
        super("Void", []);
    }
    create(value?: PartialMessage<Void>): Void {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Void>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Void): Void {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Void, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Void
 */
export const Void = new Void$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RpcError$Type extends MessageType<RpcError> {
    constructor() {
        super("RpcError", [
            { no: 1, name: "error_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RpcError>): RpcError {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.errorCode = 0;
        message.errorMessage = "";
        if (value !== undefined)
            reflectionMergePartial<RpcError>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RpcError): RpcError {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 error_code */ 1:
                    message.errorCode = reader.int32();
                    break;
                case /* string error_message */ 2:
                    message.errorMessage = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RpcError, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 error_code = 1; */
        if (message.errorCode !== 0)
            writer.tag(1, WireType.Varint).int32(message.errorCode);
        /* string error_message = 2; */
        if (message.errorMessage !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.errorMessage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RpcError
 */
export const RpcError = new RpcError$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MsgRawData$Type extends MessageType<MsgRawData> {
    constructor() {
        super("MsgRawData", [
            { no: 1, name: "seq_no", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "bytes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "class_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "body", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<MsgRawData>): MsgRawData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.seqNo = 0;
        message.msgId = 0n;
        message.bytes = 0;
        message.classId = 0;
        message.body = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<MsgRawData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MsgRawData): MsgRawData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 seq_no */ 1:
                    message.seqNo = reader.int32();
                    break;
                case /* int64 msg_id */ 2:
                    message.msgId = reader.int64().toBigInt();
                    break;
                case /* int32 bytes */ 3:
                    message.bytes = reader.int32();
                    break;
                case /* int32 class_id */ 4:
                    message.classId = reader.int32();
                    break;
                case /* bytes body */ 5:
                    message.body = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MsgRawData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 seq_no = 1; */
        if (message.seqNo !== 0)
            writer.tag(1, WireType.Varint).int32(message.seqNo);
        /* int64 msg_id = 2; */
        if (message.msgId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.msgId);
        /* int32 bytes = 3; */
        if (message.bytes !== 0)
            writer.tag(3, WireType.Varint).int32(message.bytes);
        /* int32 class_id = 4; */
        if (message.classId !== 0)
            writer.tag(4, WireType.Varint).int32(message.classId);
        /* bytes body = 5; */
        if (message.body.length)
            writer.tag(5, WireType.LengthDelimited).bytes(message.body);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MsgRawData
 */
export const MsgRawData = new MsgRawData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TMsgRawDataContainer$Type extends MessageType<TMsgRawDataContainer> {
    constructor() {
        super("TMsgRawDataContainer", [
            { no: 1, name: "messages", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MsgRawData }
        ]);
    }
    create(value?: PartialMessage<TMsgRawDataContainer>): TMsgRawDataContainer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messages = [];
        if (value !== undefined)
            reflectionMergePartial<TMsgRawDataContainer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TMsgRawDataContainer): TMsgRawDataContainer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated MsgRawData messages */ 1:
                    message.messages.push(MsgRawData.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TMsgRawDataContainer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated MsgRawData messages = 1; */
        for (let i = 0; i < message.messages.length; i++)
            MsgRawData.internalBinaryWrite(message.messages[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TMsgRawDataContainer
 */
export const TMsgRawDataContainer = new TMsgRawDataContainer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TMessage$Type extends MessageType<TMessage> {
    constructor() {
        super("TMessage", [
            { no: 1, name: "seq_no", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "bytes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "object", kind: "message", T: () => Any }
        ]);
    }
    create(value?: PartialMessage<TMessage>): TMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.seqNo = 0;
        message.msgId = 0n;
        message.bytes = 0;
        if (value !== undefined)
            reflectionMergePartial<TMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TMessage): TMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 seq_no */ 1:
                    message.seqNo = reader.int32();
                    break;
                case /* int64 msg_id */ 2:
                    message.msgId = reader.int64().toBigInt();
                    break;
                case /* int32 bytes */ 3:
                    message.bytes = reader.int32();
                    break;
                case /* google.protobuf.Any object */ 4:
                    message.object = Any.internalBinaryRead(reader, reader.uint32(), options, message.object);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 seq_no = 1; */
        if (message.seqNo !== 0)
            writer.tag(1, WireType.Varint).int32(message.seqNo);
        /* int64 msg_id = 2; */
        if (message.msgId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.msgId);
        /* int32 bytes = 3; */
        if (message.bytes !== 0)
            writer.tag(3, WireType.Varint).int32(message.bytes);
        /* google.protobuf.Any object = 4; */
        if (message.object)
            Any.internalBinaryWrite(message.object, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TMessage
 */
export const TMessage = new TMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TMsgContainer$Type extends MessageType<TMsgContainer> {
    constructor() {
        super("TMsgContainer", [
            { no: 1, name: "messages", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TMessage }
        ]);
    }
    create(value?: PartialMessage<TMsgContainer>): TMsgContainer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messages = [];
        if (value !== undefined)
            reflectionMergePartial<TMsgContainer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TMsgContainer): TMsgContainer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated TMessage messages */ 1:
                    message.messages.push(TMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TMsgContainer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated TMessage messages = 1; */
        for (let i = 0; i < message.messages.length; i++)
            TMessage.internalBinaryWrite(message.messages[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TMsgContainer
 */
export const TMsgContainer = new TMsgContainer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TGzipPacked$Type extends MessageType<TGzipPacked> {
    constructor() {
        super("TGzipPacked", [
            { no: 1, name: "packed_data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "obj", kind: "message", T: () => Any }
        ]);
    }
    create(value?: PartialMessage<TGzipPacked>): TGzipPacked {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.packedData = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<TGzipPacked>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TGzipPacked): TGzipPacked {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes packed_data */ 1:
                    message.packedData = reader.bytes();
                    break;
                case /* google.protobuf.Any obj */ 2:
                    message.obj = Any.internalBinaryRead(reader, reader.uint32(), options, message.obj);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TGzipPacked, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes packed_data = 1; */
        if (message.packedData.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.packedData);
        /* google.protobuf.Any obj = 2; */
        if (message.obj)
            Any.internalBinaryWrite(message.obj, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TGzipPacked
 */
export const TGzipPacked = new TGzipPacked$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RpcResult$Type extends MessageType<RpcResult> {
    constructor() {
        super("RpcResult", [
            { no: 1, name: "req_msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "result", kind: "message", T: () => Any }
        ]);
    }
    create(value?: PartialMessage<RpcResult>): RpcResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reqMsgId = 0n;
        if (value !== undefined)
            reflectionMergePartial<RpcResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RpcResult): RpcResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 req_msg_id */ 1:
                    message.reqMsgId = reader.int64().toBigInt();
                    break;
                case /* google.protobuf.Any result */ 2:
                    message.result = Any.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RpcResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 req_msg_id = 1; */
        if (message.reqMsgId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.reqMsgId);
        /* google.protobuf.Any result = 2; */
        if (message.result)
            Any.internalBinaryWrite(message.result, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RpcResult
 */
export const RpcResult = new RpcResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TMsgAck$Type extends MessageType<TMsgAck> {
    constructor() {
        super("TMsgAck", [
            { no: 2, name: "msg_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<TMsgAck>): TMsgAck {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.msgIds = [];
        if (value !== undefined)
            reflectionMergePartial<TMsgAck>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TMsgAck): TMsgAck {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int64 msg_ids */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.msgIds.push(reader.int64().toBigInt());
                    else
                        message.msgIds.push(reader.int64().toBigInt());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TMsgAck, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int64 msg_ids = 2; */
        if (message.msgIds.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.msgIds.length; i++)
                writer.int64(message.msgIds[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TMsgAck
 */
export const TMsgAck = new TMsgAck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BadMsgNotification$Type extends MessageType<BadMsgNotification> {
    constructor() {
        super("BadMsgNotification", [
            { no: 3, name: "bad_msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "bad_msg_seqno", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "error_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<BadMsgNotification>): BadMsgNotification {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.badMsgId = 0n;
        message.badMsgSeqno = 0;
        message.errorCode = 0;
        if (value !== undefined)
            reflectionMergePartial<BadMsgNotification>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BadMsgNotification): BadMsgNotification {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 bad_msg_id */ 3:
                    message.badMsgId = reader.int64().toBigInt();
                    break;
                case /* int32 bad_msg_seqno */ 4:
                    message.badMsgSeqno = reader.int32();
                    break;
                case /* int32 error_code */ 5:
                    message.errorCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BadMsgNotification, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 bad_msg_id = 3; */
        if (message.badMsgId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.badMsgId);
        /* int32 bad_msg_seqno = 4; */
        if (message.badMsgSeqno !== 0)
            writer.tag(4, WireType.Varint).int32(message.badMsgSeqno);
        /* int32 error_code = 5; */
        if (message.errorCode !== 0)
            writer.tag(5, WireType.Varint).int32(message.errorCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BadMsgNotification
 */
export const BadMsgNotification = new BadMsgNotification$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DestroySession$Type extends MessageType<DestroySession> {
    constructor() {
        super("DestroySession", [
            { no: 3, name: "session_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DestroySession>): DestroySession {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = 0n;
        if (value !== undefined)
            reflectionMergePartial<DestroySession>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DestroySession): DestroySession {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 session_id */ 3:
                    message.sessionId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DestroySession, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 session_id = 3; */
        if (message.sessionId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DestroySession
 */
export const DestroySession = new DestroySession$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DestroySessionOk$Type extends MessageType<DestroySessionOk> {
    constructor() {
        super("DestroySessionOk", [
            { no: 1, name: "session", kind: "message", T: () => DestroySession }
        ]);
    }
    create(value?: PartialMessage<DestroySessionOk>): DestroySessionOk {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DestroySessionOk>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DestroySessionOk): DestroySessionOk {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* DestroySession session */ 1:
                    message.session = DestroySession.internalBinaryRead(reader, reader.uint32(), options, message.session);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DestroySessionOk, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* DestroySession session = 1; */
        if (message.session)
            DestroySession.internalBinaryWrite(message.session, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DestroySessionOk
 */
export const DestroySessionOk = new DestroySessionOk$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DestroySessionNone$Type extends MessageType<DestroySessionNone> {
    constructor() {
        super("DestroySessionNone", [
            { no: 1, name: "session", kind: "message", T: () => DestroySession }
        ]);
    }
    create(value?: PartialMessage<DestroySessionNone>): DestroySessionNone {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DestroySessionNone>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DestroySessionNone): DestroySessionNone {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* DestroySession session */ 1:
                    message.session = DestroySession.internalBinaryRead(reader, reader.uint32(), options, message.session);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DestroySessionNone, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* DestroySession session = 1; */
        if (message.session)
            DestroySession.internalBinaryWrite(message.session, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DestroySessionNone
 */
export const DestroySessionNone = new DestroySessionNone$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NewSessionCreated$Type extends MessageType<NewSessionCreated> {
    constructor() {
        super("NewSessionCreated", [
            { no: 2, name: "first_msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "unique_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NewSessionCreated>): NewSessionCreated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.firstMsgId = 0n;
        message.uniqueId = 0n;
        if (value !== undefined)
            reflectionMergePartial<NewSessionCreated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NewSessionCreated): NewSessionCreated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 first_msg_id */ 2:
                    message.firstMsgId = reader.int64().toBigInt();
                    break;
                case /* int64 unique_id */ 3:
                    message.uniqueId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NewSessionCreated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 first_msg_id = 2; */
        if (message.firstMsgId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.firstMsgId);
        /* int64 unique_id = 3; */
        if (message.uniqueId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.uniqueId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message NewSessionCreated
 */
export const NewSessionCreated = new NewSessionCreated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Ping$Type extends MessageType<Ping> {
    constructor() {
        super("Ping", [
            { no: 2, name: "ping_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Ping>): Ping {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pingId = 0n;
        if (value !== undefined)
            reflectionMergePartial<Ping>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Ping): Ping {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 ping_id */ 2:
                    message.pingId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Ping, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 ping_id = 2; */
        if (message.pingId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.pingId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Ping
 */
export const Ping = new Ping$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Pong$Type extends MessageType<Pong> {
    constructor() {
        super("Pong", [
            { no: 3, name: "msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "ping_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Pong>): Pong {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.msgId = 0n;
        message.pingId = 0n;
        if (value !== undefined)
            reflectionMergePartial<Pong>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Pong): Pong {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 msg_id */ 3:
                    message.msgId = reader.int64().toBigInt();
                    break;
                case /* int64 ping_id */ 4:
                    message.pingId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Pong, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 msg_id = 3; */
        if (message.msgId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.msgId);
        /* int64 ping_id = 4; */
        if (message.pingId !== 0n)
            writer.tag(4, WireType.Varint).int64(message.pingId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pong
 */
export const Pong = new Pong$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitConnection$Type extends MessageType<InitConnection> {
    constructor() {
        super("InitConnection", [
            { no: 3, name: "api_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "device_model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "system_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "app_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "system_lang_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "lang_pack", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "lang_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "query", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<InitConnection>): InitConnection {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.apiId = 0;
        message.deviceModel = "";
        message.systemVersion = "";
        message.appVersion = "";
        message.systemLangCode = "";
        message.langPack = "";
        message.langCode = "";
        message.query = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<InitConnection>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitConnection): InitConnection {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 api_id */ 3:
                    message.apiId = reader.int32();
                    break;
                case /* string device_model */ 4:
                    message.deviceModel = reader.string();
                    break;
                case /* string system_version */ 5:
                    message.systemVersion = reader.string();
                    break;
                case /* string app_version */ 6:
                    message.appVersion = reader.string();
                    break;
                case /* string system_lang_code */ 7:
                    message.systemLangCode = reader.string();
                    break;
                case /* string lang_pack */ 8:
                    message.langPack = reader.string();
                    break;
                case /* string lang_code */ 9:
                    message.langCode = reader.string();
                    break;
                case /* bytes query */ 12:
                    message.query = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitConnection, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 api_id = 3; */
        if (message.apiId !== 0)
            writer.tag(3, WireType.Varint).int32(message.apiId);
        /* string device_model = 4; */
        if (message.deviceModel !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.deviceModel);
        /* string system_version = 5; */
        if (message.systemVersion !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.systemVersion);
        /* string app_version = 6; */
        if (message.appVersion !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.appVersion);
        /* string system_lang_code = 7; */
        if (message.systemLangCode !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.systemLangCode);
        /* string lang_pack = 8; */
        if (message.langPack !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.langPack);
        /* string lang_code = 9; */
        if (message.langCode !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.langCode);
        /* bytes query = 12; */
        if (message.query.length)
            writer.tag(12, WireType.LengthDelimited).bytes(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InitConnection
 */
export const InitConnection = new InitConnection$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthIdInfo$Type extends MessageType<AuthIdInfo> {
    constructor() {
        super("AuthIdInfo", [
            { no: 3, name: "auth_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "session_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "auth_key", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<AuthIdInfo>): AuthIdInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.authId = 0n;
        message.sessionId = 0n;
        message.authKey = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<AuthIdInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthIdInfo): AuthIdInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 auth_id */ 3:
                    message.authId = reader.int64().toBigInt();
                    break;
                case /* int64 session_id */ 4:
                    message.sessionId = reader.int64().toBigInt();
                    break;
                case /* bytes auth_key */ 5:
                    message.authKey = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthIdInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 auth_id = 3; */
        if (message.authId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.authId);
        /* int64 session_id = 4; */
        if (message.sessionId !== 0n)
            writer.tag(4, WireType.Varint).int64(message.sessionId);
        /* bytes auth_key = 5; */
        if (message.authKey.length)
            writer.tag(5, WireType.LengthDelimited).bytes(message.authKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AuthIdInfo
 */
export const AuthIdInfo = new AuthIdInfo$Type();
