import type {Metadata} from "next";
import "./globals.css";
import {AppProvider} from "@/components/Providers/AppProvider";
import {WebSocketProvider} from "@/components/WebSocket/provider";
import React from "react";
import {ThemeProvider} from "@/components/Layout/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`antialiased`}
    >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <WebSocketProvider>
        <AppProvider>
          {children}
        </AppProvider>
      </WebSocketProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
