import type {Metadata} from "next";
import "./globals.css";
import {AppProvider} from "@/components/Providers/AppProvider";
import {WebSocketProvider} from "@/components/WebSocket/provider";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`antialiased`}
    >
    <WebSocketProvider>
      <AppProvider>
        {children}
      </AppProvider>
    </WebSocketProvider>
    </body>
    </html>
  );
}
