import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {MatomoProvider} from "@cesnow/matomo-next";
import {AppProvider} from "@/components/Providers/AppProvider";
import {TProtoProvider} from "@/components/TProto/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MatomoProvider>
          <TProtoProvider>
            <AppProvider>
              {children}
            </AppProvider>
          </TProtoProvider>
        </MatomoProvider>
      </body>
    </html>
  );
}
