// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: configuration.proto

package configurationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	tproto "kiyudesign.com/cesnow/light-server/pkg/tproto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RpcConfiguration_HelpGetCountriesList_FullMethodName = "/configuration.RpcConfiguration/help_getCountriesList"
	RpcConfiguration_HelpTryNotifyUser_FullMethodName    = "/configuration.RpcConfiguration/help_tryNotifyUser"
)

// RpcConfigurationClient is the client API for RpcConfiguration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcConfigurationClient interface {
	HelpGetCountriesList(ctx context.Context, in *THelpGetCountriesList, opts ...grpc.CallOption) (*Help_CountriesList, error)
	HelpTryNotifyUser(ctx context.Context, in *THelpTryNotifyUser, opts ...grpc.CallOption) (*tproto.Bool, error)
}

type rpcConfigurationClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcConfigurationClient(cc grpc.ClientConnInterface) RpcConfigurationClient {
	return &rpcConfigurationClient{cc}
}

func (c *rpcConfigurationClient) HelpGetCountriesList(ctx context.Context, in *THelpGetCountriesList, opts ...grpc.CallOption) (*Help_CountriesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Help_CountriesList)
	err := c.cc.Invoke(ctx, RpcConfiguration_HelpGetCountriesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcConfigurationClient) HelpTryNotifyUser(ctx context.Context, in *THelpTryNotifyUser, opts ...grpc.CallOption) (*tproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(tproto.Bool)
	err := c.cc.Invoke(ctx, RpcConfiguration_HelpTryNotifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcConfigurationServer is the server API for RpcConfiguration service.
// All implementations should embed UnimplementedRpcConfigurationServer
// for forward compatibility
type RpcConfigurationServer interface {
	HelpGetCountriesList(context.Context, *THelpGetCountriesList) (*Help_CountriesList, error)
	HelpTryNotifyUser(context.Context, *THelpTryNotifyUser) (*tproto.Bool, error)
}

// UnimplementedRpcConfigurationServer should be embedded to have forward compatible implementations.
type UnimplementedRpcConfigurationServer struct {
}

func (UnimplementedRpcConfigurationServer) HelpGetCountriesList(context.Context, *THelpGetCountriesList) (*Help_CountriesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelpGetCountriesList not implemented")
}
func (UnimplementedRpcConfigurationServer) HelpTryNotifyUser(context.Context, *THelpTryNotifyUser) (*tproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelpTryNotifyUser not implemented")
}

// UnsafeRpcConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcConfigurationServer will
// result in compilation errors.
type UnsafeRpcConfigurationServer interface {
	mustEmbedUnimplementedRpcConfigurationServer()
}

func RegisterRpcConfigurationServer(s grpc.ServiceRegistrar, srv RpcConfigurationServer) {
	s.RegisterService(&RpcConfiguration_ServiceDesc, srv)
}

func _RpcConfiguration_HelpGetCountriesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(THelpGetCountriesList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcConfigurationServer).HelpGetCountriesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcConfiguration_HelpGetCountriesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcConfigurationServer).HelpGetCountriesList(ctx, req.(*THelpGetCountriesList))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcConfiguration_HelpTryNotifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(THelpTryNotifyUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcConfigurationServer).HelpTryNotifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcConfiguration_HelpTryNotifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcConfigurationServer).HelpTryNotifyUser(ctx, req.(*THelpTryNotifyUser))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcConfiguration_ServiceDesc is the grpc.ServiceDesc for RpcConfiguration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcConfiguration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configuration.RpcConfiguration",
	HandlerType: (*RpcConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "help_getCountriesList",
			Handler:    _RpcConfiguration_HelpGetCountriesList_Handler,
		},
		{
			MethodName: "help_tryNotifyUser",
			Handler:    _RpcConfiguration_HelpTryNotifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}
